### PR TITLE
Updated static class diagram of whole system for final project

### PR DESCRIPTION
**Pull request by RayMuhlenkamp**
I have updated the static class diagram, need to push it to master so the links in the project still work

### CODE REVIEW

**Comment by RayMuhlenkamp** [comment]
there is this annoying issue with the auto merge still, I'm not entirely sure how to fix it this time though

**Review by nathan-inge — COMMENTED** [review]
Is the Rick and Morty jpg supposed to be in there haha?

**Comment by RayMuhlenkamp** [comment]
Yes

**Comment by RayMuhlenkamp** [comment]
It's very important science stuff

**Review by nathan-inge — APPROVED** [review]
Sounds good to me!

**Pull request merged**
